### ISSUE TITLE
Gyroscope

### ISSUE THREAD

**Issue by camblomquist** [Pierre-Demessence/NFC-Ball-Maze-Game#24]
As it exists now, the gyroscope directly correlates to the angle of the platform. Ideally, the angle is set as the offset from a neutral point. A button should reset the controller to zero so that the current gyroscope position is the neutral position. Implementing this in Controller is an easy fix, making sure this works with all the objects that move in the maze will be more difficult.

**Comment by Pierre-Demessence** [comment]
Moving that for 1.0 as the current movement works far good enough.
